### ISSUE TITLE
inferExtension doesn't work with typescript def

### ISSUE THREAD

**Issue by kierans** [polyforest/jsdoc-tsimport-plugin#3]
I'm wanting to use this plugin with my project where the source is in Javascript, but we have types defined in Typescript that's imported from a company module (we also have local TS defs to the project). Because the types are in [TS declaration files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html), they have a `.d.ts` extension.

If I try to type my JS var and then generate the documentation, it fails.

For example

```javascript
// mycode.js

// Assume MyType is in 'MyType.d.ts'
/** @type {import('../../types/MyType').SomeInterface} */
const obj = {};
```

```
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at inferExtension (/Project/node_modules/jsdoc-tsimport-plugin/index.js:188:15)
```

Looking at [the source](https://github.com/polyforest/jsdoc-tsimport-plugin/blob/main/index.js#L188) I think it's because `path.extname` is not stripping off the `.d` which means that `MyType` !== `MyType.d` so `find` returns `undefined` which causes `join` to blow up.

```
> path.extname("Foo.ts")
'.ts'
> path.extname("Foo.d.ts")
'.ts'
```

A possible solution would be to substring from the first `.` found eg: `filename.substring(0, filename.indexOf("."))` This would see `MyType.d.ts` and `MyType.ts` become `MyType`

**Comment by nbilyk** [comment]
I hadn't considered/tried the TS definition case. I suspect JSDoc won't be able to understand TS files, you'll likely need TSDoc for that. However, there does seem to be a bug you're describing where this plugin shouldn't fail if the jsdoc points to a .d.ts file. I'll check it out and possibly make a separate ticket. 

PR requests are also welcome if you come up with a simple solution.

**Comment by kierans** [comment]
Thanks @nbilyk.

I'm using a plugin called [better-docs](https://github.com/SoftwareBrothers/better-docs) to incorporate the TS defs into JSDoc. This is a much better solution where I can use TS defs to describe my types than have to create JSDoc comments

**Comment by kierans** [comment]
> PR requests are also welcome if you come up with a simple solution.

I did propose a solution in the ticket, however I don't know if that's sufficient.

**Comment by nbilyk** [comment]
It might be, I'm looking into it. The question is how does TypeScript expect to resolve the file. For example if foo.bar.js should be referenced in the import as "foo.bar" that would break, so I'm doing a few tests first.

**Comment by nbilyk** [comment]
I've identified 3 cases to handle -

* if the JS file has a dot in the name such as foo.bar.js
* If the TS file is named foo.d.ts and referenced as import('foo')
* If the TS file is named foo.d.ts and referenced as import('foo.d')

**Comment by nbilyk** [comment]
Give 1.0.4 a try

**Comment by kierans** [comment]
Thanks.
