### ISSUE TITLE
Imports with @ prefix

### ISSUE THREAD

**Issue by creack** [polyforest/jsdoc-tsimport-plugin#4]
Hello,

Thank you for this plugin, it is really an awesome tool!

Would it be possible to add support for '@' in the import path?

I am not 100% sure, but I think my errors are coming from the plugin not processing those. Each time I try to do somethingn like  `{import('@xxx/xx').xx}`, I am getting a parse error from jsdoc.

Example:

```js
/** @type {import('@google-cloud/firestore').DocumentData} */
const data = {}
```

```sh
ERROR: Unable to parse a tag's type expression for source file lib/firestore.js in line 2 with tag title "type" and text "{import('@google-cloud/firestore').DocumentData}": Invalid type expression "import('@google-cloud/firestore').DocumentData": Expected "!", "=", "?", "[]", "|", or end of input but "(" found.
```

In the case of firebase, I can work around the issue by using `import('firebase-admin')`, but for other libs, it is not an option.

**Comment by bombitmanbomb** [comment]
Also getting this issue, Only thing holding back right now is My packages use '@'

**Comment by nbilyk** [comment]
Thanks for the PR!
