### ISSUE TITLE
Add support for '&'

### ISSUE THREAD

**Issue by creack** [polyforest/jsdoc-tsimport-plugin#5]
Hello,

In the spirit of support typescript style docs, would it be possible to add support for the `&` operator to compose types? Typescript handles it well, but JSDoc really doesn't like it.

I am no expert and have very little experience, but from what I can see, if the plugin would simply replace '&' by '|', it would make JSDoc happy and will let Typescript understand the types properly.

**Comment by nbilyk** [comment]
> Typescript handles it well

Could you explain what you mean there? Do you mean IntelliSense handles it well?

**Comment by lekoala** [comment]
i had the same issue, found this plugin: https://github.com/chriseaton/jsdoc-plugin-intersection
